spring.application.name=TicketBookingApplicaton

spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
# ✅ Gmail SMTP Config for OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=routeone0110@gmail.com
spring.mail.password=ealqmdqitrqndzye
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true






